library1/books/urls.py
from django.contrib import admin
from django.urls import path
from books import views
app_name="books"
urlpatterns = [
     path('',views.home,name='home'),
     path('view',views.viewbooks,name='view'),
     path('add',views.addbooks,name='add'),
     path('detail/<int:p>',views.detail,name='detail'),
     path('delete/<int:p>', views.delete, name='delete'),
     path('edit/<int:p>', views.edit, name='edit'),
]

library1/library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('users/',include('users.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

library1/users/urls.py
from django.contrib import admin
from django.urls import path
from users import views

app_name="users"

urlpatterns = [
    path('userregister',views.userregister,name='userregister'),
    path('adminregister',views.adminregister,name='adminregister'),
    path('login',views.user_login,name='login'),
    path('logout',views.user_logout,name='logout'),
    path('vu',views.view_user,name='vu'),
]

library1/books/models.py
from django.db import models

# Create your models here.

#model definition
class Book(models.Model):
    title=models.CharField(max_length=20)
    author = models.CharField(max_length=20)
    price=models.IntegerField()
    pages=models.IntegerField()
    language = models.CharField(max_length=20)
    cover=models.ImageField(upload_to="cover")
    pdf=models.FileField(upload_to="pdf")


    def __str__(self):
        return self.title
          #return self.author

library1/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
#model definition
class Users(models.Model):
    name=models.CharField(max_length=20)
    age=models.IntegerField()
    place = models.CharField(max_length=20)
    gender = models.CharField(max_length=2)


class CustomUser(AbstractUser):
    phone=models.BigIntegerField(default=0)
    address=models.CharField(max_length=20,default="")
    is_superuser = models.BooleanField(default=False)
    is_user=models.BooleanField(default=False)

library1/books/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.
def home(request):#home view
    return render(request, 'home.html')

from books.models import Book
@login_required
def viewbooks(request):#index view

    k=Book.objects.all()  #reads all records from tge book table
    context={'book':k}    #sends data from view function to html page
    return render(request,'view.html',context)
@login_required
def addbooks(request):#index view
    if(request.method=="POST"):
        t=request.POST['t']
        a = request.POST['a']
        p = request.POST['p']
        pa = request.POST['pa']
        l = request.POST['l']
        i=request.FILES.get('i')
        f=request.FILES.get('f')
        b=Book.objects.create(title=t,author=a,price=p,pages=pa,language=l,cover=i,pdf=f)
        b.save()
        return viewbooks(request)
    return render(request, 'add.html')

@login_required
def detail(request,p):
    k=Book.objects.get(id=p) #reads a particular record
    context={'particular':k}
    return render(request, 'detail.html',context)

@login_required
def delete(request,p):
    k=Book.objects.get(id=p)
    k.delete()
    return redirect('books:view')
@login_required
def edit(request,p):
    k = Book.objects.get(id=p)
    if (request.method == "POST"):
        k.title = request.POST['t']
        k.author= request.POST['a']
        k.price= request.POST['p']
        k.pages= request.POST['pa']
        k.language = request.POST['l']
        if(request.FILES.get('i')==None):
            k.save()
        else:
            k.cover=request.FILES.get('i')

        if(request.FILES.get('f')==None):
            k.save()
        else:
            k.pdf=request.FILES.get('f')

        k.save()
        return redirect('books:view')

    context={'edit':k}
    return render(request, 'edit.html',context)

library1/users/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,authenticate,logout
from users.models import CustomUser
# Create your views here.
def userregister(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p = request.POST['p']
        cp = request.POST['cp']
        f = request.POST['f']
        l = request.POST['l']
        e=request.FILES.get('e')
        n=request.POST['n']
        a=request.POST['a']
        if(p==cp):
            u=CustomUser.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l,phone=n,address=a,is_user=True)
            u.save()
            return redirect('books:home')
        else:
            return HttpResponse("Passwords are not same")


    return render(request, 'userregister.html')

def adminregister(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p = request.POST['p']
        cp = request.POST['cp']
        f = request.POST['f']
        l = request.POST['l']
        e=request.FILES.get('e')
        n=request.POST['n']
        a=request.POST['a']
        if(p==cp):
            u=CustomUser.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l,phone=n,address=a,is_superuser=True)
            u.save()
            return redirect('books:home')
        else:
            return HttpResponse("Passwords are not same")


    return render(request, 'adminregister.html')

def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p = request.POST['p']
        user=authenticate(username=u,password=p)
        if user and user.is_superuser==True:
            login(request,user)
            return redirect('books:home')
        elif user and user.is_user==True:
            login(request, user)
            return redirect('books:home')
        else:#if no matching user
            return HttpResponse("Invalid Credentials")

    return render(request, 'login.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect('users:login')

from users.models import Users
def view_user(request):
    g = Users.objects.all()
    context = {'using': g}
    return render(request, 'viewusers.html',context)

library1/templates/add.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-3"> Add book details </h2>
<div class="container w-50">
<form method="POST"  enctype="multipart/form-data">

  {% csrf_token %}
  <div class="mb-3">
    <label  class="form-label">Title</label>
    <input type="text" class="form-control" name="t" placeholder="TITLE" >

  </div>

  <div class="mb-3">
    <label  class="form-label">Author</label>
    <input type="text" class="form-control" name="a" placeholder="Author">
  </div>
  <div class="mb-3">
    <label  class="form-label">Price</label>
    <input type="number" class="form-control" name="p" placeholder="Price">
  </div>
<div class="mb-3">
    <label  class="form-label">Pages</label>
    <input type="number" class="form-control" name="pa" placeholder="input number">
  </div>
  <div class="mb-3">
    <label  class="form-label">Language</label>
    <input type="text" class="form-control" name="l" placeholder="Enter language">
  </div>
  <div class="mb-3">
    <label  class="form-label">Cover</label>
    <input type="file" class="form-control" name="i" >
  </div>

  <div class="mb-3">
    <label  class="form-label">Pdf</label>
    <input type="file" class="form-control" name="f" >
  </div>

  <div class="mb-3">
    <input type="submit" class="form-control btn btn-primary" >
  </div>
</form>
</div>
{% endblock %}

library1/templates/adminregister.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h2 class="text-center mt-3">Admin Registration form</h2>
<div class="container  mb-5">
<form method="POST">

  {% csrf_token %}
 <div class="mb-3">
    <label  class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="username">
  </div>

     <div class="mb-3">
    <label  class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="password">
  </div>
    <div class="mb-3">
    <label  class="form-label">Confirm Password</label>
    <input type="password" class="form-control" name="cp" placeholder="re-enter password">
  </div>

     <div class="mb-3">
    <label  class="form-label">First name</label>
    <input type="text" class="form-control" name="f" placeholder="enter first name">
  </div>

     <div class="mb-3">
    <label  class="form-label">Last name</label>
    <input type="text" class="form-control" name="l" placeholder="last name">
  </div>
      <div class="mb-3">
    <label  class="form-label">Email</label>
    <input type="email" class="form-control" name="e" placeholder="enter email">
  </div>


          <div class="mb-3">
    <label  class="form-label">Phone</label>
    <input type="number" class="form-control" name="n" placeholder="enter phone number">
  </div>

          <div class="mb-3">
    <label  class="form-label">Address</label>
    <input type="text" class="form-control" name="a" placeholder="enter address">
  </div>
        <div class="mb-3">
  <input  type="submit" class="form-control" >
</div>
</form>
    </div>
{% endblock %}

library1/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-secondary ">
  <div class="container">
    <a class="navbar-brand fs-3 text-light" href="#">Library App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 fw-bold fs-4 mb-lg-0 ">
        <li class="nav-item">
          <a class="nav-link active text-light" aria-current="page" href="{% url 'books:home' %}">Home</a>
        </li>
         {% if user.is_authenticated %}
         {% if user.is_superuser == True %}
          <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'books:add' %}">Add books</a>
        </li>
        {% endif %}
          <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'books:view' %}">View books</a>
        </li>
                <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'users:logout' %}">Logout</a>
        </li>

        {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link text-light dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Register
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'users:userregister' %}">User Registration</a></li>
            <li><a class="dropdown-item" href="{% url 'users:adminregister' %}">Admin Registration</a></li>

          </ul>

        <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'users:login' %}">Login</a>
        </li>



        <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'users:vu' %}">View users</a>
        </li>

         {% endif %}
      </ul>

    </div>
  </div>
</nav>
{% block content %}
hello
{% endblock %}
</body>
</html>

library1/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-3">Book Details</h2>
<div class="card mb-3 mt-5 mx-auto p-4" style="max-width: 650px;">
  <div class="row g-0">
    <div class="col-md-4 p-2">
      <img src="{{particular.cover.url}}" class="rounded-start" alt="..." height="250px" width="200px">
    </div>
    <div class="col-md-8 lh-lg ps-5">
      <div class="card-body mt-2">
        <p class="card-title"><strong>TITLE : </strong>{{particular.title}}</p>
        <p class="card-text"><strong>AUTHOR : </strong>{{particular.author}}</p>
          <p class="card-text"><strong>LANGUAGE : </strong>{{particular.language}}</p>
          <p class="card-text"><strong>PRICE :</strong>{{particular.price}}</p>
          <a href="{{particular.pdf.url}}" class="btn btn-danger">DOWNLOAD</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

library1/templates/edit.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-3">Edit book details</h2>
<div class="container w-50">
<form method="POST" enctype="multipart/form-data">

  {% csrf_token %}
  <div class="mb-3">
    <label  class="form-label">Title</label>
    <input type="text" class="form-control" name="t" value="{{edit.title}}" placeholder="TITLE" >

  </div>

  <div class="mb-3">
    <label  class="form-label">Author</label>
    <input type="text" class="form-control" name="a" value="{{edit.author}}" placeholder="Author">
  </div>
  <div class="mb-3">
    <label  class="form-label">Price</label>
    <input type="number" class="form-control" name="p" value="{{edit.price}}" placeholder="Price">
  </div>
<div class="mb-3">
    <label  class="form-label">Pages</label>
    <input type="number" class="form-control" name="pa" value="{{edit.pages}}" placeholder="input number">
  </div>
  <div class="mb-3">
    <label  class="form-label">Language</label>
    <input type="text" class="form-control" name="l" value="{{edit.language}}" placeholder="Enter language">
  </div>
  <div class="mb-3">
    <label  class="form-label">Cover</label>
            <img src="{{edit.cover.url}}" height="100px" width="100px">
    <input type="file" class="form-control" name="i" >
  </div>

  <div class="mb-3">
    <label  class="form-label">Pdf</label>
            <a href="{{edit.pdf.url}}">{{edit.pdf}}</a>
    <input type="file" class="form-control" name="f" >
  </div>

  <div class="mb-3">
    <input type="submit" class="form-control btn btn-light" value="Submit" >
  </div>
</form>
</div>
{% endblock %}

library1/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-3">Welcome to Home page</h2>

{% endblock %}

library1/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-3">Welcome to Login page</h2>

<div class="container  mt-5 w-50">
<form method="POST">
 {% csrf_token %}
      <div class="mb-3">
    <label  class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="enter username">
  </div>
    <div class="mb-3">
    <label  class="form-label">Password</label>
    <input type="text" class="form-control" name="p" placeholder="enter password">
  </div>
        <div class="mb-3">
  <input  type="submit" class="form-control" >
</div>
</form>
</div>
{% endblock %}

library1/templates/userregister.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h2 class="text-center mt-3">User Registration form</h2>
<div class="container  mb-5">
<form method="POST">

  {% csrf_token %}
 <div class="mb-3">
    <label  class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="username">
  </div>

     <div class="mb-3">
    <label  class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="password">
  </div>
    <div class="mb-3">
    <label  class="form-label">Confirm Password</label>
    <input type="password" class="form-control" name="cp" placeholder="re-enter password">
  </div>

     <div class="mb-3">
    <label  class="form-label">First name</label>
    <input type="text" class="form-control" name="f" placeholder="enter first name">
  </div>

     <div class="mb-3">
    <label  class="form-label">Last name</label>
    <input type="text" class="form-control" name="l" placeholder="last name">
  </div>
      <div class="mb-3">
    <label  class="form-label">Email</label>
    <input type="email" class="form-control" name="e" placeholder="enter email">
  </div>


          <div class="mb-3">
    <label  class="form-label">Phone</label>
    <input type="number" class="form-control" name="n" placeholder="enter phone number">
  </div>

          <div class="mb-3">
    <label  class="form-label">Address</label>
    <input type="text" class="form-control" name="a" placeholder="enter address">
  </div>
        <div class="mb-3">
  <input  type="submit" class="form-control" >
</div>
</form>
    </div>
{% endblock %}

library1/templates/view.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h2 class="text-center mt-3 mb-3">List of books </h2>
<table class="table table-bordered border border-1 border-info text-dark">
    <tr>
         <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PRICE</th>
        <th>PAGES</th>
        <th>LANGUAGE</th>
        <th>PDF</th>
        <th>VIEW</th>
        <th>EDIT</th>
        <th>DELETE</th>

    </tr>
{% for i in  book %}

<tr>
     <td><img src="{{i.cover.url}}" height="100px" width="100px"></td>
<td>{{i.title}}</td>
<td>{{i.author}}</td>
<td>{{i.price}}</td>
<td>{{i.pages}}</td>
    <td>{{i.language}}</td>

    <td><a href="{{i.pdf.url}}" class="text-dark">DOWNLOAD</a></td>
    <td><a href="{% url 'books:detail' i.id %}" class="btn btn-outline-dark">view</a></td>
    <td><a href="{% url 'books:edit' i.id  %}" class="btn btn-outline-dark">edit</a></td>
    <td><a href="{% url 'books:delete' i.id %}" class="btn btn-outline-dark">delete</a></td>
</tr>
{% endfor %}
</table>

<!--<ol>-->
<!--    {% for i in book %}-->
<!--    <li>Book details:</li>-->
<!--    <ul>-->
<!--        <li>Title: {{i.title}}</li>-->
<!--        <li>Author: {{i.author}}</li>-->
<!--        <li>Price: {{i.price}}</li>-->
<!--    </ul>-->
<!--     {% endfor %}-->
<!--</ol>-->




{% endblock %}

library1/templates/viewusers.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Welcome to View user's page</h2>
{{using}}
<ol>
    {% for i in using %}
    <li>User Records:</li>
    <ul>
        <li>Name: {{i.name}}</li>
        <li>Age: {{i.age}}</li>
        <li>Place: {{i.place}}</li>
         <li>Gender: {{i.gender}}</li>
    </ul>
     {% endfor %}
</ol>



<h2>User Records</h2>
<table>
    <tr>

       <th>NAME</th>
        <th>AGE</th>
        <th>PLACE</th>
        <th>GENDER</th>

    </tr>
{% for i in  using %}

<tr>
<td>{{i.name}}</td>
<td>{{i.age}}</td>
<td>{{i.place}}</td>
<td>{{i.gender}}</td>

</tr>
{% endfor %}
</table>

{% endblock %}